path: ./models/edof_models.py
type: Net
batch_size: 16
epochs: 300
kargs:
    target_mode: 
    skip_layer: true
    mode: segmentation
loss: CrossEntropyLoss
loss_kargs:
    ignore_index: 0
    reduction: mean

perfomance_measurements:
    pixelwize_accuracy:
        path: ./performance_measurements.py
        type: PixelWiseAccuracy

