path: ./models/Unet-milesial.py
type: UNet
batch_size: 3
epochs: 400
kargs:
    n_channels: 3
    n_classes: 16
    bilinear: True
loss: CrossEntropyLoss
loss_kargs:
    ignore_index: 0
    reduction: mean

perfomance_measurements:
    pixelwize_accuracy:
        path: ./performance_measurements.py
        type: PixelWiseAccuracy

