path: ./models/Unet-milesial.py
type: UNet
batch_size: 16
epochs: 600
in_channels: &in_ch 3
out_channels: &out_c 3
kargs:
    n_channels: *in_ch
    n_classes: *out_c
    scale_channels: 64
#loss: CrossEntropyLoss # SmoothL1Loss
loss:
    MS_SSIM_Loss:
        module_path: pytorch_msssim
        kargs:
            data_range: 1
            weights: [ 0.0448, 0.2856, 0.3001 ]
            K: [0.01, 0.4]
    SmoothL1Loss:
        kargs:
            reduction: mean
            #mix_alpha: 0.84
test_traces:
    image_trace:
        path: ./traces.py
        type: ImageTrace
train_traces:

